system:
  base_directory: "/Users/sytsevanderschaaf/documents/dev/projects/ai_workbench"
  directories:
    input_directory: "{base_directory}/input"
    output_directory: "{base_directory}/output"
    test_directory: "{base_directory}/tests"
    model_settings_directory: "{base_directory}/ai_model_core"
    config_directory: "{base_directory}/ai_model_core/config"

system_prompt_settings:
  english:
    system_prompt: "You are a helpful AI assistant that speaks English."
  dutch:
    system_prompt: "Je bent een behulpzame AI-assistent die Nederlands spreekt."

# Language specific prompts
prompts:
  english:
    RAG-Prompt: |
      Context information:
      {context}

      Question: {question}

      Instructions:
      1. Use only the information provided in the context above to formulate your answer
      2. Format your response to be clear, well-readable, and concise
      3. Maintain a friendly, professional tone suitable for marketing purposes
      4. When referencing information, cite specific parts from the context
      5. If the context doesn't contain sufficient information to answer the question, clearly state this and specify what additional information would be needed
      
      Answer:
    Python Code Optimizer and Debugger: |
      Analyze the following Python code:
      [Paste existing code here]

      1. Identify potential issues or inefficiencies in the code.
      2. Suggest improvements to make the code more readable and efficient.
      3. If there are specific bugs, explain how to fix them.
      4. Provide an improved version of the code with comments on the changes.
      5. Propose a testing strategy to validate the improved code.

      Focus on [specific aspect or functionality] and consider [any limitations or requirements].
    summarize_stuff: |
      Write a concise summary of the following text in 4 sentences:
      "{text}"
      Focus on the main ideas and key points. Avoid including minor details.
      CONCISE SUMMARY:
    summarize_map: |
      Analyze the following set of documents:
      {docs}
      
      Your task is to:
      1. Identify the 3-5 main themes or key points from these documents.
      2. For each theme or key point:
        a. Provide a brief 1-2 sentence explanation.
        b. Include a specific example or short quote from the documents to support this theme (if available).
      3. Maintain the original tone and style of the documents in your analysis.
      
      Format your response as follows:
      Theme 1: [Theme title]
      Explanation: [1-2 sentence explanation]
      Example/Quote: "[relevant quote or example]"
      
      Theme 2: [Theme title]
      Explanation: [1-2 sentence explanation]
      Example/Quote: "[relevant quote or example]"
      
      [Continue for up to 5 themes]
      
      Note: Ensure your entire response is no more than 250 words.
    summarize_map_reduce: |
      Analyze the following chunk of text:
      {docs}
      Identify and list the 3-5 main themes or key points from this chunk. 
      For each theme or key point, provide a brief 1-2 sentence explanation.
      Themes:
      1.
      2.
      3.
      4.
      5.
    reduce_template: |
      Below is a set of themes and key points extracted from different chunks of a larger text:
      {docs}
      Your task is to:
      1. Identify the most recurring and significant themes across all chunks.
      2. Consolidate similar themes.
      3. Provide a final, coherent summary of 3-5 main themes or key points that represent the entire text.
      4. Ensure your summary is concise (150-200 words) and captures the essence of the original text.

      Final Summary:
    summarize_refine: |
      Your task is to refine and improve an existing summary of a text.

      Existing summary:
      {existing_answer}

      New context to consider:
      {text}

      Instructions:
      1. Carefully read the existing summary and the new context.
      2. Identify any new, important information in the context that is missing from the existing summary.
      3. Determine if the new information significantly changes or adds to the main points of the existing summary.
      4. If the new context is relevant:
        - Incorporate the new information into the existing summary.
        - Ensure the refined summary remains concise (no more than 25% longer than the original).
        - Maintain a coherent flow of ideas.
      5. If the new context isn't useful or doesn't add significant value:
        - Return the original summary unchanged.

      Refined Summary:
    Transcribe Assistant: |
      Analyze the uploaded image (original filename: {input_file_name}) and provide the following information in Markdown format:
      
      1. The printed text in the image (if any)

      2. The handwritten notes or annotations in the image (if any)

      Format your response as follows:
      # Original File: {input_file_name}

      # Printed Text
      [Printed text content here]

      # Handwritten Notes
      [Handwritten notes content here]

      If either printed text or handwritten notes are not present, include the heading but leave the content blank.
    
    Translation Assistant: "You're a handy translation assistant. Translate my text from Dutch into English and vice versa. Just provide the translation results in a natural manner."
    
    Chain of Thought Analyzer: |
      Analyze the following problem: [describe problem]. Use a chain of thought approach to unfold your reasoning. Start by identifying core components, consider different options, evaluate pros and cons, and conclude with a recommendation. Think out loud at each step.
    
    Tree of Thoughts: |
      Solve the following problem: [problem]. Use the Tree of Thoughts method. Generate three initial thoughts, develop each into two follow-up steps, and evaluate which path is most promising.
    
    Least-to-Most: |
      We're going to tackle [complex task]. Let's start by identifying the smallest, most basic subtask. Solve that first, and use that result to approach the next, slightly more complex subtask. Continue this process until the main task is completed.
    
    Few-Shot Chain-of-Thought: |
      Here are two examples of [problem type] with worked-out solutions:
      [Example 1 with step-by-step explanation]
      [Example 2 with step-by-step explanation]
      Now solve the following problem in the same way: [new problem]
    
    Vision Assistant: |
      Check if the uploaded image has the correct orientation for optimal visual recognition. If the image is twisted, rotate it for optimal image recognition by humans and machines. Give a short description of what you see in the image with a maximum of 10 words in MD.

# language_specific:
  dutch:
    RAG-Prompt: |
      Context informatie:
      {context}

      Vraag: {question}

      Instructies:
      1. Gebruik alleen de informatie uit de bovenstaande context om je antwoord te formuleren
      2. Formuleer je antwoord duidelijk, goed leesbaar en beknopt
      3. Houd een vriendelijke, professionele toon aan die past bij marketingdoeleinden
      4. Verwijs bij het delen van informatie naar specifieke delen uit de context
      5. Als de context onvoldoende informatie bevat om de vraag te beantwoorden, geef dit duidelijk aan en specificeer welke aanvullende informatie nodig zou zijn

      Antwoord:
    summarize_stuff: |
      Schrijf een beknopte samenvatting van de volgende tekst in 4 zinnen:
      "{text}"
      Concentreer je op de hoofdideeën en kernpunten. Vermijd het opnemen van kleine details.
      BEKNOPTE SAMENVATTING:
    summarize_map: |
      Analyseer de volgende verzameling documenten:
      {docs}

      Je taak is om:

      De 3-5 belangrijkste thema’s of kernpunten uit deze documenten te identificeren.
      Voor elk thema of kernpunt: 
      a. Geef een korte uitleg van 1-2 zinnen. 
      b. Voeg een specifiek voorbeeld of een kort citaat uit de documenten toe ter ondersteuning van dit thema (indien beschikbaar).
      Behoud de oorspronkelijke toon en stijl van de documenten in je analyse.
      Formatteer je antwoord als volgt: 
      Thema 1: [Thematitel]
      Uitleg: [1-2 zinnen uitleg]
      Voorbeeld/Citaat: "[relevant citaat of voorbeeld]"

      Thema 2: [Thematitel]
      Uitleg: [1-2 zinnen uitleg]
      Voorbeeld/Citaat: "[relevant citaat of voorbeeld]"

      [Ga door voor maximaal 5 thema’s]

      Let op: zorg ervoor dat je gehele antwoord niet meer dan 250 woorden bevat.
    summarize_map_reduce: |
      Analyseer het volgende tekstfragment:
      {docs}
      Identificeer en maak een lijst van de 3-5 hoofdthema's of kernpunten uit dit fragment.
      Geef voor elk thema of kernpunt een korte uitleg van 1-2 zinnen.
      Thema's:
      1.
      2.
      3.
      4.
      5.
    reduce_template: |
      Hieronder staat een reeks thema's en kernpunten die zijn geëxtraheerd uit verschillende fragmenten van een grotere tekst:
      {docs}
      Jouw taak is om:
      1. De meest voorkomende en belangrijke thema's in alle fragmenten te identificeren.
      2. Vergelijkbare thema's samen te voegen.
      3. Een definitieve, samenhangende samenvatting te geven van 3-5 hoofdthema's of kernpunten die de hele tekst vertegenwoordigen.
      4. Ervoor te zorgen dat je samenvatting beknopt is (150-200 woorden) en de essentie van de originele tekst weergeeft.

      Samenvatting:
    summarize_refine: |
      Je taak is om een bestaande samenvatting van een tekst te verfijnen en te verbeteren.

      Bestaande samenvatting:
      {existing_answer}

      Nieuwe context om te overwegen:
      {text}

      Instructies:
      1. Lees de bestaande samenvatting en de nieuwe context zorgvuldig.
      2. Identificeer eventuele nieuwe, belangrijke informatie in de context die ontbreekt in de bestaande samenvatting.
      3. Bepaal of de nieuwe informatie de hoofdpunten van de bestaande samenvatting significant verandert of aanvult.
      4. Als de nieuwe context relevant is:
        - Verwerk de nieuwe informatie in de bestaande samenvatting.
        - Zorg ervoor dat de verfijnde samenvatting beknopt blijft (niet meer dan 25% langer dan het origineel).
        - Behoud een samenhangende gedachtenstroom.
      5. Als de nieuwe context niet bruikbaar is of geen significante waarde toevoegt:
        - Geef de originele samenvatting ongewijzigd terug.

      Verfijnde Samenvatting:
    Concept Analyzer: |
      Analyseer [concept X] in deze tekst, en beschrijf hoe het resoneert met [specifieke doelgroep]. Denk stap voor stap.
      
    Constrained Content Generator: |
      Schrijf 3 nieuwe versies van de inleiding, rekening houdend met [recente markttrend]. Volg deze constraints: [lijst].
      
    Step-by-Step Evaluator: |
      Evalueer deze opzet op conversiekracht voor [doelgroep]. Wat werkt goed en wat kan beter? Analyseer per onderdeel.
      
    Concise Context Responder: |
      Geef prikkelende antwoorden van 10-15 woorden op deze vragen, gebaseerd op de context. Eindig elk antwoord met een call-to-action.
      
    Blog Improvement Extractor: |
      Identificeer verbeterpunten in deze blog die direct bijdragen aan [specifiek marketingdoel]. Herformuleer voor maximale impact.
      
    Industry Wisdom Challenger: |
      Noem 10 conventionele wijsheden op in [industrie]. Daag ze uit met jouw unieke inzichten en voorspel hun relevantie over 5 jaar.
      
    Incremental Summary Refiner: |
      Vat dit artikel samen, focus op [Brand Entity 1, 2, 3]. Voeg stapsgewijs [Brand USP 1, 2, etc.] toe zonder de lengte te vergroten.