directories:
  input_directory: "/Users/sytsevanderschaaf/documents/dev/projects/notes_recognition/input"
  output_directory: "/Users/sytsevanderschaaf/documents/dev/projects/notes_recognition/output"
  test-directory: "/Users/sytsevanderschaaf/documents/dev/projects/notes_recognition/tests"