system:
  directories:
    input_directory: "/Users/sytsevanderschaaf/documents/dev/projects/notes_recognition/input"
    output_directory: "/Users/sytsevanderschaaf/documents/dev/projects/notes_recognition/output"
    test_directory: "/Users/sytsevanderschaaf/documents/dev/projects/notes_recognition/tests"

prompts:
  Vision Assistant: "Check if the uploaded image has the correct orientation for optimal visual recognition. If the image is twisted, rotate it for optimal image recognition by humans and machines. Give a short description of what you see in the image with a maximum of 10 words in MD."
  Transcribe Assistant: "Analyze the uploaded image (original filename: {input_file_name}) and provide the following information in Markdown format:
    
              1. The printed text in the image (if any)

              2. The handwritten notes or annotations in the image (if any)

              Format your response as follows:
              # Original File: {input_file_name}

              # Printed Text
              [Printed text content here]

              # Handwritten Notes
              [Handwritten notes content here]

              If either printed text or handwritten notes are not present, include the heading but leave the content blank."
  Translation Assistant: "You're a handy translation assistant. Translate my text from Dutch into English and vice versa. Just provide the translation results in a natural manner."