[tool.poetry]
name = "notetaking-conversion"
version = "0.1.0"
description = "A project to convert handwritten notes to digital text using LLaVA and Ollama"
authors = ["Sytse van der Schaaf <sytse@svdschaaf.nl>"]
packages = [{include = "notetaking_conversion"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
tqdm = "^4.65.0"
pyyaml = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"